# Generated by Django 4.2.4 on 2023-08-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varitation_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='varitation_value',
            new_name='variation_value',
        ),
    ]
